import Head from 'next/head'
import CallsList from '../components/CallsList'
import { refreshToken } from '../utils/API';
import { useEffect } from 'react';

export default function Home() {
  const startInterval = () => {
    const intervalStartTime = new Date().getTime();
    localStorage.setItem("intervalStartTime", intervalStartTime);
    setInterval(refreshToken().then((response) => {
          localStorage.setItem('turingUserToken', response?.data?.access_token)
          localStorage.setItem('turingRefreshToken', response?.data?.refresh_token)
        })
        .catch((error) => {
          console.log(error)
        }), 600000);
  };
  
  const checkInterval = () => {
    const intervalStartTime = localStorage.getItem("intervalStartTime");
    if (intervalStartTime) {
      const currentTime = new Date().getTime();
      const timeElapsed = currentTime - parseInt(intervalStartTime, 10);
      const remainingTime = 590000 - timeElapsed;
      if (remainingTime > 0) {
        setTimeout(() => {
          startInterval();
        }, remainingTime);
      } else {
      }
    } else {
      startInterval();
    }
  };
  useEffect(() => {
    checkInterval()
  }, []);
  return (
    <div>
      <Head>
        <title>Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <CallsList />
    </div>
  )
}
