export const stylesMui = {
  headerButton: {
    px: "30px",
    textAlign: "center",
    fontFamily: "Avenir-Book",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 300,
    textTransform: "none",
    borderRadius: "6px",
    background: "#4f46f8 !important",
    color: "#fff",
  },
  loginButton: {
    px: "15px",
    textAlign: "center",
    fontFamily: "Avenir-Book",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 300,
    textTransform: "none",
    borderRadius: "6px",
    background: "#1890FF !important",
    color: "#fff",
  },
  actionsButton: {
    px: "15px",
    textAlign: "center",
    fontFamily: "Avenir-Book",
    fontSize: "15px",
    fontStyle: "normal",
    fontWeight: 300,
    textTransform: "none",
    borderRadius: "6px",
    background: "#4f46f8 !important",
    color: "#fff",
  },
};
