export const CRUD_ACTION = {
  ADD_REQUEST: 'ADD_REQUEST',
  ADD_SUCCESS: 'ADD_SUCCESS',
  ADD_FAILURE: 'ADD_FAILURE',
  
  EDIT_REQUEST: 'EDIT_REQUEST',
  EDIT_SUCCESS: 'EDIT_SUCCESS',
  EDIT_FAILURE: 'EDIT_FAILURE',
  
  VIEW_REQUEST: 'VIEW_REQUEST',
  VIEW_SUCCESS: 'VIEW_SUCCESS',
  VIEW_FAILURE: 'VIEW_FAILURE',
  
  DELETE_REQUEST: 'DELETE_REQUEST',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAILURE: 'DELETE_FAILURE',
};

export const LISTING_ACTIONS = {
  GET_REQUEST: 'GET_LISTING_REQUEST',
  GET_SUCCESS: 'GET_LISTING_SUCCESS',
  GET_FAILURE: 'GET_LISTING_FAILURE',
};

export const USER_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};

export const GENERAL_ACTIONS = {
  ACTIVE_TOKEN_CHECK_REQUEST: 'INACTIVE_TOKEN_CHECK_REQUEST',
  ACTIVE_TOKEN_CHECK_SUCCESS: 'INACTIVE_TOKEN_CHECK_SUCCESS',
  ACTIVE_TOKEN_CHECK_FAILURE: 'INACTIVE_TOKEN_CHECK_FAILURE',

  GET_DOWNLOAD_FILE_REQUEST:'GET_DOWNLOAD_FILE_REQUEST',
  GET_DOWNLOAD_FILE_SUCCESS:'GET_DOWNLOAD_FILE_SUCCESS',
  GET_DOWNLOAD_FILE_FAILURE:'GET_DOWNLOAD_FILE_FAILURE'
}
