import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@/context/loginState'
import Nav from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Turing task',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Nav></Nav>
          {children}
          
          </UserProvider>
       </body>
    </html>
  )
}
