import type { Metadata } from 'next'

import './globals.css'
import Navbar from '@/components/ui/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='h-full'>
      <body className='h-full font-avenirBlack'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
