import AntdRegistry from '@/lib/AntdRegistry'
import { LayoutWrapper } from '@/styles/layout.styles'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AntdRegistry>
            <LayoutWrapper>
              <div>Navbar</div>
              {children}
            </LayoutWrapper>
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
