export const app = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  PUSHER_APP_AUTH_ENDPOINT: process.env.NEXT_PUBLIC_PUSHER_APP_AUTH_ENDPOINT,
  PUSHER_APP_KEY: process.env.NEXT_PUBLIC_PUSHER_APP_KEY,
  PUSHER_APP_CLUSTER: process.env.NEXT_PUBLIC_PUSHER_APP_CLUSTER,
};
